service: cmr-stac-api

provider:
  name: aws
  runtime: nodejs14.x
  stage: dit
  region: ${env:AWS_REGION}

functions:
  search-api:
    handler: lib/application.handler
    events:
      - http:
          path: /
          method: GET
      - http:
          path: /{proxy+}
          method: any
    environment:
      CMR_URL: 'https://cmr.uat.nncpp.org,https://cmr.maap-project.org'
      CMR_STAC_RELATIVE_ROOT_URL: /stac
      CMR_STAC_PROTOCOL: ${env:PROTOCOL, 'https'}
      LOG_LEVEL: info
      LOG_DISABLED: false
      STAC_VERSION: 1.0.0
      BROWSE_PATH: year/month/day

custom:
  serverless-offline:
    port: 3000

plugins:
  - serverless-offline
